/**
 * Domain types for the ATRIX storefront.
 *
 * These are deliberately shaped like a commerce backend's output rather than
 * like the components that render them. When Shopify/Medusa/Stripe is wired
 * up, the adapter in src/lib/catalog.ts maps the API response into these
 * shapes and no component has to change. See docs/architecture.md.
 */

export type CurrencyCode = "BGN" | "EUR";

/**
 * Money is stored in minor units (stotinki, cents) as an integer. Floats are
 * never used for money anywhere in this codebase — 79.90 * 3 is not 239.70 in
 * binary floating point, and a cart is exactly where that surfaces.
 */
export interface Money {
  amount: number;
  currency: CurrencyCode;
}

export type SizeCode = "XS" | "S" | "M" | "L" | "XL" | "XXL";

export type ProductCategory = "t-shirt" | "longsleeve" | "hoodie" | "accessory";

/**
 * `status` drives what the UI offers, not just what it says:
 *   available     — buyable
 *   sold-out      — shown, not buyable, kept in the grid as proof of scarcity
 *   in-production — announced, no photography yet; renders as a typographic card
 *   archived      — past drops, reachable by URL, excluded from listings
 */
export type ProductStatus = "available" | "sold-out" | "in-production" | "archived";

/** How a shot frames the garment. Drives gallery order and caption defaults. */
export type ShotRole = "front" | "back" | "worn" | "detail" | "still";

export interface ProductImage {
  src: string;
  alt: string;
  width: number;
  height: number;
  /** Inline LQIP generated by scripts/prepare-media.mjs. */
  blurDataURL?: string;
  role: ShotRole;
  caption?: string;
}

export interface ColorOption {
  /** Stable machine value used in URLs and variant keys. */
  code: string;
  name: string;
  /** Swatch fill. The real garment colour, not a UI colour. */
  hex: string;
}

/**
 * One purchasable combination. `sku` is the unit of inventory and the key the
 * cart stores — never the product id, or two sizes would collapse into one line.
 */
export interface ProductVariant {
  sku: string;
  size: SizeCode;
  colorCode: string;
  /** Units on hand. 0 means sold out for this combination only. */
  inventory: number;
}

export interface SpecRow {
  label: string;
  value: string;
}

export interface Product {
  id: string;
  slug: string;
  name: string;
  /** One line of editorial voice. Used on cards, in search, in meta tags. */
  tagline: string;
  /** Long copy for the product page. Plain paragraphs, no markup. */
  description: string[];
  price: Money;
  /** Set only when a piece is genuinely discounted. */
  compareAtPrice?: Money;
  status: ProductStatus;
  category: ProductCategory;
  /** The drop this piece belongs to. */
  dropId: string;
  images: ProductImage[];
  colors: ColorOption[];
  sizes: SizeCode[];
  variants: ProductVariant[];
  specs: SpecRow[];
  care: string[];
  /** Units made. The whole positioning rests on this being small and true. */
  editionSize?: number;
  featured?: boolean;
  /** ISO date. Used for sorting and for Product structured data. */
  releasedAt?: string;
}

export interface Drop {
  id: string;
  slug: string;
  /** Display index, zero-padded: "01". */
  number: string;
  title: string;
  subtitle: string;
  /** The editorial statement shown on the drop page. */
  statement: string[];
  /** Where and when, e.g. "VARNA 2026". */
  season: string;
  releasedAt: string;
  cover: ProductImage;
}

export interface LookbookFrame {
  id: string;
  image: ProductImage;
  /** Optional link through to the piece worn in the frame. */
  productSlug?: string;
  /** Layout weight — the lookbook alternates these to build rhythm. */
  scale: "full" | "wide" | "tall" | "inset";
  caption?: string;
}

/* ── Cart ──────────────────────────────────────────────────────────────── */

/**
 * A cart line stores the sku plus a denormalised snapshot of what the customer
 * saw. If a price or name changes after an item is in someone's bag, we can
 * detect the drift at checkout instead of silently repricing their cart.
 */
export interface CartLine {
  sku: string;
  productId: string;
  slug: string;
  name: string;
  size: SizeCode;
  colorName: string;
  quantity: number;
  unitPrice: Money;
  image: Pick<ProductImage, "src" | "alt" | "width" | "height" | "blurDataURL">;
}

/* ── Catalog querying ──────────────────────────────────────────────────── */

export type SortKey = "featured" | "newest" | "price-asc" | "price-desc";

export interface CatalogFilters {
  category?: ProductCategory[];
  size?: SizeCode[];
  color?: string[];
  /** Inclusive bounds in minor units. */
  priceMin?: number;
  priceMax?: number;
  /** Hide sold-out and in-production pieces. */
  availableOnly?: boolean;
  dropId?: string;
}
